name: fhnw
channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- jupyter=1.0.0
- matplotlib
- pandas=1.1.5
- scipy
- numpy
- lmfit
- ipykernel
- ipython
- ipywidgets
- voila
- jupyter_contrib_nbextensions
- pip:
  - plotly-express
  - jupyterlab
  

