name: fhnw
channels:
- conda-forge
- defaults
dependencies:
- python>=3.8
- jupyter
- matplotlib
- pandas
- scipy
- numpy
- lmfit
- ipykernel
- ipython
- ipywidgets
- voila
- jupyter_contrib_nbextensions
- pip:
  - plotly-express
  - jupyterlab
  

